common/models/Center.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%center}}".
 *
 * @property integer $id
 * @property string $center_name
 * @property integer $city
 * @property integer $locality
 * @property integer $state
 * @property string $description
 * @property string $added_on
 * @property string $updated_on
 * @property integer $added_by
 * @property integer $updated_by
 * @property integer $status
 *
 * @property City $city0
 * @property Locality $locality0
 * @property State $state0
 */
class Center extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%center}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['center_name'], 'required'],
            [['city', 'locality', 'state', 'added_by', 'updated_by', 'status'], 'integer'],
            [['description'], 'string'],
            [['added_on', 'updated_on'], 'safe'],
            [['center_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'center_name' => 'Center Name',
            'city' => 'City',
            'locality' => 'Locality',
            'state' => 'State',
            'description' => 'Description',
            'added_on' => 'Added On',
            'updated_on' => 'Updated On',
            'added_by' => 'Added By',
            'updated_by' => 'Updated By',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity0()
    {
        return $this->hasOne(City::className(), ['id' => 'city']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocality0()
    {
        return $this->hasOne(Locality::className(), ['id' => 'locality']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState0()
    {
        return $this->hasOne(State::className(), ['id' => 'state']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSocialcredentials()
    {
        return $this->hasOne(SocialIntegration::className(), ['company_id' => 'id']);
    }
}

models/Center.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%center}}".
 *
 * @property integer $id
 * @property string $center_name
 * @property integer $city
 * @property integer $locality
 * @property integer $state
 * @property string $description
 * @property string $added_on
 * @property string $updated_on
 * @property integer $added_by
 * @property integer $updated_by
 * @property integer $status
 *
 * @property City $city0
 * @property Locality $locality0
 * @property State $state0
 */
class Center extends \yii\db\ActiveRecord
{
    public $role,$subrole,$excel;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%center}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['center_name', 'city', 'locality', 'state', 'description', 'added_by', 'updated_by', 'status'], 'required'],
            [['city', 'locality', 'state', 'added_by', 'updated_by', 'status'], 'integer'],
            [['description'], 'string'],
            [['added_on', 'updated_on'], 'safe'],
            [['center_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'center_name' => 'Center Name',
            'city' => 'City',
            'locality' => 'Locality',
            'state' => 'State',
            'description' => 'Description',
            'added_on' => 'Added On',
            'updated_on' => 'Updated On',
            'added_by' => 'Added By',
            'updated_by' => 'Updated By',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity0()
    {
        return $this->hasOne(City::className(), ['id' => 'city']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocality0()
    {
        return $this->hasOne(Locality::className(), ['id' => 'locality']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState0()
    {
        return $this->hasOne(State::className(), ['id' => 'state']);
    }
}

controllers/CenterController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Center;
use yii\data\ActiveDataProvider;
use app\components\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * CenterController implements the CRUD actions for Center model.
 */
class CenterController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete', 'index', 'upload-users', 'get-subroles', 'download-sample'],
                'rules' => [
                    [
                        'actions' => ['create', 'update', 'delete', 'index', 'upload-users', 'get-subroles', 'download-sample'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Center models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new \app\models\CenterSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Center model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Center model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Center();
        $model_admin = new \app\models\CenterUser();
        if ($model->load(Yii::$app->request->post()) && $model_admin->load(Yii::$app->request->post())) {
            $model->added_by = Yii::$app->user->identity->id;
            $model->updated_by = Yii::$app->user->identity->id;
            $model->updated_on = date('Y-m-d H:i:s');
            $model->added_on = date('Y-m-d H:i:s');
            $model_admin->added_by = Yii::$app->user->identity->id;
            $model_admin->updated_by = Yii::$app->user->identity->id;
            $model_admin->updated_on = date('Y-m-d H:i:s');
            $model_admin->added_on = date('Y-m-d H:i:s');
            $model->validate();
            $model_admin->validate(["first_name", "last_name", "email", "mobile"]);
            if (!$model->hasErrors() && !$model_admin->hasErrors()) {
                if ($model->save(FALSE)) {
                    $model_admin->center_id = $model->id;
                    $model_admin->role = 7;
                    $pwd = '123456';
                    $model_admin->password = sha1($pwd);
                    $model_admin->status = $model->status;
                    if ($model_admin->save(FALSE)) {
                        $this->sendviaMandrill($model_admin->email, "TraQ Password", "Password : $pwd", $this->adminEmail, $this->adminName, "Admin User Created");
                        return $this->redirect(['index']);
                    }
                }
            }
        } //else {
        return $this->render('_form', [
                    'model' => $model,
                    'model_admin' => $model_admin
        ]);
        //}
    }

    /**
     * Updates an existing Center model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $model_admin = \app\models\CenterUser::find()->where("center_id = :center_id AND role = :role", [":center_id" => $model->id, ":role" => 7])->one();
        if (!isset($model_admin->id)) {
            $model_admin = new \app\models\CenterUser();
        }
        if ($model->load(Yii::$app->request->post()) && $model_admin->load(Yii::$app->request->post())) {
            $model->updated_by = Yii::$app->user->identity->id;
            $model->updated_on = date('Y-m-d H:i:s');
            $model_admin->updated_by = Yii::$app->user->identity->id;
            $model_admin->updated_on = date('Y-m-d H:i:s');
            $model->validate();
            $model_admin->validate(["first_name", "last_name", "email", "mobile"]);
            if (!$model->hasErrors() && !$model_admin->hasErrors()) {
                if ($model->save(FALSE)) {
                    $isnew = $model_admin->isNewRecord;
                    $pwd = sha1('123456');
                    if ($isnew) {
                        $model_admin->center_id = $model->id;
                        $model_admin->role = 7;
                        $model_admin->password = $pwd;
                    }
                    $model_admin->status = $model->status;
                    if ($model_admin->save(FALSE)) {
                        if ($isnew)
                            $this->sendviaMandrill($model_admin->email, "TraQ Password", "Password : $pwd", $this->adminEmail, $this->adminName, "Admin User Created");
                        return $this->redirect(['index']);
                    }
                }
            }
        } //else {
        return $this->render('_form', [
                    'model' => $model,
                    'model_admin' => $model_admin
        ]);
        //}
    }

    /**
     * Deletes an existing Center model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Center model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Center the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Center::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionUploadUsers($id) {

        $center_model = $this->findModel($id);
        if (Yii::$app->request->post()) {
            /* $val_model = \yii\base\DynamicModel::validateData(compact('role', 'subrole', 'excel'));
              $val_model->addRule(["role"], 'required')
              ->validate(); */
            $data = Yii::$app->request->post();
            if (isset($data['Center'])) {
                $data = $data['Center'];
            }
            if (!isset($data["role"]) || $data["role"] == '') {
                $center_model->addError('role', "Role Is Required");
            } else {
                $center_model->role = $data["role"];
            }
            $excel = \yii\web\UploadedFile::getInstance($center_model, 'excel');

            if (is_null($excel)) {
                $center_model->addError('excel', "Excel File Is Required");
            } else {
                if ($excel->error != 0) {
                    $center_model->addError('excel', "Error in upload");
                }
                if (!isset($excel->extension) || !in_array(strtolower($excel->extension), ["xlx", "xlsx"])) {
                    $center_model->addError('excel', "Invalid files , xlx,xlsx");
                }
            }
            if (!$center_model->hasErrors()) {
                $name = $center_model->id . "_" . time() . "_" . $excel->baseName . "." . $excel->extension;
                $path = "excel_upload/$name";
                $excel->saveAs($path);
                require_once \Yii::getAlias('@app') . '/common/libraries/PHPExcel/Classes/PHPExcel.php';
                $objPHPExcel = \PHPExcel_IOFactory::load($path);
                $sheetData = $objPHPExcel->getActiveSheet()->toArray(null, true, true, true);
                $columns = [];
                $allColumns = [];
                if (isset($sheetData[1])) {
                    $columns = $sheetData[1];
                    unset($sheetData[1]);
                }
                if (count($sheetData)) {
                    $tobeinsert = count($sheetData);
//                    $sql = \Yii::$app->db->createCommand()->batchInsert(\app\models\CenterUser::tableName(), $columns, $sheetData)->getRawSql();
//                    $inserted = \Yii::$app->db->createCommand()->batchInsert(\app\models\CenterUser::tableName(), $columns, $sheetData)->execute();
                    $errors = '';
                    $filtered_data = [];
                    $batch_tag = $id . "_" . time();
                    $excelStr = "";
                    $emails = $mobiles = [];
                    foreach ($sheetData as $row) {
                        $rdata_copy = $row;
                        $rdata = array_combine($columns, $row);

                        $rdata['center_id'] = $id;
                        $rdata['batch_tag'] = $batch_tag;
                        $rdata['role'] = isset($data['role']) ? $data['role'] : 0;
                        $rdata['sub_role'] = isset($data['subrole']) ? $data['subrole'] : 0;
                        $rdata['status'] = 1;
                        $rdata['added_on'] = $rdata['updated_on'] = date('Y-m-d H:i:s');
                        $rdata['added_by'] = $rdata['updated_by'] = isset(\Yii::$app->user->identity->id) ? \Yii::$app->user->identity->id : 0;
                        $pwd = '123456';
                        $rdata['password'] = sha1($pwd);
                        /*

controllers/ServiceController.php
<?php
namespace app\controllers;

class ServiceController extends \app\components\Controller{
    public function actionGetCity(){
        $state_id = isset($_REQUEST['state_id']) ? $_REQUEST['state_id'] : "";
        $dataSet = [];
        if($state_id != ""){
            $cities = \app\models\City::find()->select(["id","city"])->where(["state"=>$state_id])->asArray()->all();
            $dataSet = \yii\helpers\ArrayHelper::map($cities, 'id', 'city');
        }
        echo "<option value=''>Select City</option>";
        foreach ($dataSet as $id=>$city){
            echo "<option value='$id'>$city</option>";
        }
    }
    public function actionGetLocality(){
        $city_id = isset($_REQUEST['city_id']) ? $_REQUEST['city_id'] : "";
        $dataSet = [];
        if($city_id != ""){
            $localities = \app\models\Locality::find()->select(["id","locality"])->where(["city"=>$city_id])->asArray()->all();
            $dataSet = \yii\helpers\ArrayHelper::map($localities, 'id', 'locality');
        }
        echo "<option value=''>Select Locality</option>";
        foreach ($dataSet as $id=>$city){
            echo "<option value='$id'>$city</option>";
        }
    }
}

views/center/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Center */
/* @var $form yii\widgets\ActiveForm */
$this->title = ($model->isNewRecord) ? 'Add Centers' : "Update Center | {$model->center_name}";
$this->registerJsFile(Yii::$app->request->baseUrl."/js/select2.min.js",
        ['depends' => [
            yii\bootstrap\BootstrapAsset::className(),
             yii\web\JqueryAsset::className()
            ]
        ]
      );
$this->registerCssFile(Yii::$app->request->baseUrl."/css/select2.css",
        ['depends' => [yii\bootstrap\BootstrapAsset::className()],]
      );
?>

<div class="center-form">

    <?php $form = ActiveForm::begin([
        /*'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],*/
        'fieldConfig' => [
//            'template' => "<div class='col-md-6'>{label}{input}{error}</div>",
//            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
//            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'center_name')->textInput(['maxlength' => 255]) ?>
    <?php
        $states = \app\models\State::find()->all();
        $states = \yii\helpers\ArrayHelper::map($states, 'id', 'state');
    ?>
    <?= $form->field($model, 'state')->dropDownList($states,
    [
        "prompt"=>"Select State",
        "class"=>'form-control select2-use',
        "onchange"=>"$('#center-city').html('<option val=\"\">Select City</option>');"
        . "$('#center-locality').html('<option val=\"\">Select Locality</option>');"
        . " $.post('".Yii::$app->urlManager->createAbsoluteUrl(['service/get-city'])."',{state_id:$(this).val()},function(res){"
        . "$('#center-city').html(res);"
        . "}) "
    ]) ?>
    <?php
    $cityList = [];
    if(isset($model->state)){
         $cities = \app\models\City::find()->select(["id","city"])->where(["state"=>$model->state])->asArray()->all();
         $cityList = \yii\helpers\ArrayHelper::map($cities, 'id', 'city');
    }
    ?>
    <?= $form->field($model, 'city')->dropDownList($cityList,
            [
                "prompt" => "Select City",
                "onchange"=>"$('#center-locality').html('<option val=\"\">Select Locality</option>');"
                . " $.post('".Yii::$app->urlManager->createAbsoluteUrl(['service/get-locality'])."',{city_id:$(this).val()},function(res){"
                . "$('#center-locality').html(res);"
                . "}) "
            ]
            ) ?>
    <?php
    $localityList = [];
    if(isset($model->city)){
        $localities = \app\models\Locality::find()->select(["id","locality"])->where(["city"=>$model->city])->asArray()->all();
        $localityList = yii\helpers\ArrayHelper::map($localities, 'id', 'locality');
    }
    ?>
    <?= $form->field($model, 'locality')->dropDownList($localityList,["prompt"=>"Select Locality"]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
    
    <?= $form->field($model_admin, 'first_name')->textInput(['maxlength' => 255]) ?>
    
    <?= $form->field($model_admin, 'last_name')->textInput(['maxlength' => 255]) ?>
    
    <?= $form->field($model_admin, 'email')->textInput(['maxlength' => 255]) ?>
    
    <?= $form->field($model_admin, 'mobile')->textInput(['maxlength' => 10,'minlength'=>10]) ?>

    <?= $form->field($model, 'status')->dropDownList(["1"=>"Active","0"=>"In Active"]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/center/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Centers';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="center-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Center', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php yii\widgets\Pjax::begin(["timeout"=>10000,'clientOptions'=>['container'=>'pajax-container']]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel'=>$searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'center_name',
            [
                'attribute'=>'city',
                'value'=>'city0.city'
            ],
            [
                'attribute'=>'locality',
                'value'=>'locality0.locality'
            ],
            [
                'attribute'=>'state',
                'value'=>'state0.state'
            ],
            [
                'attribute'=>'status',
                'value'=>  function ($data){
                    return isset($data->status) && $data->status ? "Active" : "InActive";
                },
                "filter"=> Html::activeDropDownList($searchModel, 'status',["1"=>"Active","0"=>"InActive"],['class'=>'form-control','prompt' => 'Status'])
            ],
            // 'description:ntext',
            // 'added_on',
            // 'updated_on',
            // 'added_by',
            // 'updated_by',
            // 'status',

            [
                'class' => 'yii\grid\ActionColumn',
                'template'=>'{upload-users}&nbsp{update}&nbsp;{delete}',
                'buttons'=> [
                    'upload-users'=>function ($url, $model, $key) {
                        return Html::a('Upload Users', $url);
                    }
                ]
            ],
        ],
    ]); ?>
    <?php yii\widgets\Pjax::end(); ?>

</div>

views/center/users-upload.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

//$this->title =  "Update Center | {$model->center_name}";
?>
<div class="center-form">
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <?php
        $roles = \app\models\Role::find()
                ->select(["id","role"])
                ->where("status AND id IN (2,3,4,5,6)")
                ->all();
        $roles = \yii\helpers\ArrayHelper::map($roles, 'id', 'role');
    ?>
    <?= $form->field($model, 'role')->dropDownList($roles,
    [
        "prompt"=>"Select Role",
        "class"=>'form-control select2-use',
        "onchange"=>"$('#center-subrole').html('<option val=\"\">Select Subrole</option>');"
            . "$.post('".Yii::$app->urlManager->createAbsoluteUrl(["center/get-subroles","center_id"=>$model->id])."',{role_id:$(this).val()},function(res){"
            . "$('#center-subrole').html(res);"
            . "})"
    ]) ?>
    <?= $form->field($model, 'subrole')->dropDownList([],
    [
      "prompt"=>"Select SubRole",  
      "class"=>'form-control select2-use',
    ]        
    ); ?>
    <?= $form->field($model, 'excel')->fileInput(); ?>
    <div class="form-group">
        <?= Html::submitButton('Upload', ['class' => 'btn btn-primary']) ?>
        Download Sample excel : <a href="<?php echo Yii::$app->urlManager->createAbsoluteUrl(["center/download-sample","file"=>'trainers']) ?>">Trainers</a> | 
        <a href="<?php echo Yii::$app->urlManager->createAbsoluteUrl(["center/download-sample","file"=>'members']) ?>">Members</a>
    </div>
    <?php ActiveForm::end(); ?>
</div>